"use client";
import { useEffect,useState } from 'react';
import { supabase } from '@/lib/supabase';
import { Field } from './primitives';
import type { Plant } from '@/lib/data';
import { POPULAR_LOCATIONS } from '@/lib/locations';
import { LocationMap } from './location-map';
type Report={id:string;crop:string;body:string;locality:string;status:string};
type Alert={id:string;crop:string;body:string;locality:string;read:boolean};
export function CropSafety({owner,plants}:{owner:string;plants:Plant[]}){
 const [reports,setReports]=useState<Report[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[admin,setAdmin]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [lat,setLat]=useState(''),[lon,setLon]=useState(''),[locality,setLocality]=useState(''),[crop,setCrop]=useState(plants[0]?.crop||''),[body,setBody]=useState('');
 const [contentType,setContentType]=useState('post'),[contentId,setContentId]=useState(''),[showMap,setShowMap]=useState(false);
 async function refresh(){const db=supabase();const [r,a,role,l]=await Promise.all([db.from('crop_reports').select('id,crop,body,locality,status').order('created_at',{ascending:false}).limit(50),db.from('alerts').select('id,crop,body,locality,read').order('created_at',{ascending:false}).limit(100),db.rpc('is_rootory_admin'),db.from('grower_locations').select('latitude,longitude,locality').eq('owner_id',owner).maybeSingle()]);if(r.error||a.error||role.error||l.error)throw Error('Crop alerts are not ready. Apply the crop-safety migration.');setReports(r.data||[]);setAlerts(a.data||[]);setAdmin(Boolean(role.data));if(l.data){setLat(String(l.data.latitude));setLon(String(l.data.longitude));setLocality(l.data.locality);}}
 useEffect(()=>{void refresh().catch(e=>setMessage(e.message));},[owner]);
 async function run(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'Action failed');}finally{setBusy(false);}}
 return <section className="panel margin-bottom"><h2>Crop reports near you</h2><p>Reviewed reports can alert growers of the same crop within 10 km. Reports must be less than seven days old. Coordinates stay private; other growers see only the area and report.</p>
 <button className="button secondary" disabled={busy} onClick={()=>void run(refresh)}>Refresh crop alerts</button>
 <details><summary>Set your private alert area</summary><form className="form" onSubmit={e=>{e.preventDefault();void run(async()=>{const latitude=Number(lat),longitude=Number(lon);if(!lat||!lon||!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180)throw Error('Enter valid coordinates.');const r=await supabase().from('grower_locations').upsert({owner_id:owner,latitude:Math.round(latitude*100)/100,longitude:Math.round(longitude*100)/100,locality:locality.trim()});if(r.error)throw Error('Could not save alert area.');setMessage('Private alert area saved.');});}}>
 <div style={{marginBottom:10}}><span style={{fontSize:11,color:'#758766',display:'block',marginBottom:4}}>Quick-fill from popular regions:</span><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{POPULAR_LOCATIONS.slice(0,8).map(loc=><button key={loc.name} type="button" className="sample-tag" style={{cursor:'pointer'}} onClick={()=>{setLocality(loc.name);setLat(loc.lat.toFixed(2));setLon(loc.lon.toFixed(2));}}>{loc.name}</button>)}</div></div>
 <div style={{display:'flex',gap:8,alignItems:'center',marginBottom:8}}><button type="button" className="button secondary" style={{padding:'5px 10px',fontSize:12}} onClick={()=>setShowMap(!showMap)}>{showMap?'Hide map':'🗺️ Pin on map'}</button><button type="button" className="text-button" onClick={()=>{if(!navigator.geolocation){setMessage('Location unavailable; enter coordinates.');return;}navigator.geolocation.getCurrentPosition(p=>{setLat(p.coords.latitude.toFixed(2));setLon(p.coords.longitude.toFixed(2));},()=>setMessage('Location unavailable; enter coordinates.'),{timeout:10000});}}>Use my location</button></div>
 {showMap&&<LocationMap initialLat={Number(lat)||15.46} initialLon={Number(lon)||73.88} initialLabel={locality||'Selected area'} onSelectLocation={(newLat,newLon,label)=>{setLat(newLat.toFixed(2));setLon(newLon.toFixed(2));setLocality(label);setShowMap(false);}} onClose={()=>setShowMap(false)}/>}
 <Field label="Area name"><input required maxLength={150} value={locality} onChange={e=>setLocality(e.target.value)} placeholder="e.g. Pune"/></Field><Field label="Latitude"><input type="number" step="any" min={-90} max={90} required value={lat} onChange={e=>setLat(e.target.value)}/></Field><Field label="Longitude"><input type="number" step="any" min={-180} max={180} required value={lon} onChange={e=>setLon(e.target.value)}/></Field><button disabled={busy} className="button primary">Save alert area</button></form></details>
 <form className="form margin-top" onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await supabase().from('crop_reports').insert({owner_id:owner,crop:crop.trim(),body:body.trim()});if(r.error)throw Error('Could not submit report. Save your alert area first.');setBody('');await refresh();setMessage('Report submitted for administrator review. No alert is sent until approved.');});}}><Field label="Affected crop"><input required maxLength={100} value={crop} onChange={e=>setCrop(e.target.value)} list="grown-crops"/><datalist id="grown-crops">{[...new Set(plants.map(p=>p.crop))].map(c=><option key={c}>{c}</option>)}</datalist></Field><Field label="Observed symptoms"><textarea required maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="Describe what you observed. Do not include personal contact details."/></Field><button className="button primary" disabled={busy}>Submit for review</button></form>
 {message&&<p role="status">{message}</p>}
 <h3 className="margin-top">Nearby reviewed alerts</h3>{!alerts.length&&<p>No matching alerts yet.</p>}{alerts.map(a=><article key={a.id} className="panel"><strong>{a.crop} · {a.locality}</strong><p>{a.body}</p>{!a.read&&<button className="text-button" disabled={busy} onClick={()=>void run(async()=>{const r=await supabase().from('alerts').update({read:true}).eq('id',a.id);if(r.error)throw Error('Could not mark alert read.');await refresh();})}>Mark read</button>}</article>)}
 <h3 className="margin-top">{admin?'Report review queue':'Your reports'}</h3>{reports.map(r=><article className="panel" key={r.id}><strong>{r.crop} · {r.status}</strong><p>{r.body}</p>{admin&&r.status==='Pending'&&<div className="row"><button disabled={busy} className="button primary" onClick={()=>void run(async()=>{const result=await supabase().rpc('review_crop_report',{report:r.id,approve:true});if(result.error)throw Error(result.error.message);await refresh();setMessage(`Reviewed. ${result.data} nearby growers notified in-app.`);})}>Approve and notify</button><button disabled={busy} className="button secondary" onClick={()=>void run(async()=>{const result=await supabase().rpc('review_crop_report',{report:r.id,approve:false});if(result.error)throw Error(result.error.message);await refresh();})}>Reject</button></div>}</article>)}
 {admin&&<details><summary>Content moderation</summary><form className="form" onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await supabase().rpc('moderate_content',{content_type:contentType,content_id:contentId});if(r.error)throw Error(r.error.message);setMessage('Moderation action applied.');});}}><Field label="Content type"><select value={contentType} onChange={e=>setContentType(e.target.value)}><option value="post">Post (remove)</option><option value="listing">Listing (mark unavailable)</option></select></Field><Field label="Content ID"><input required value={contentId} onChange={e=>setContentId(e.target.value)}/></Field><button className="button secondary" disabled={busy}>Apply moderation</button></form></details>}
 </section>;
}
