"use client";
import { useState } from "react";
type Weather={temperature:number;humidity:number;wind:number;rainProbability:number|null;time:string;timezone:string};
export function LiveWeather(){
 const [weather,setWeather]=useState<Weather|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[place,setPlace]=useState("Pune");
 async function load(lat:number,lon:number,label:string){setBusy(true);setError("");try{const r=await fetch(`/api/weather?latitude=${lat.toFixed(2)}&longitude=${lon.toFixed(2)}`);const b=await r.json();if(!r.ok)throw Error(b.error);setWeather(b);setPlace(label);}catch(e){setError(e instanceof Error?e.message:"Weather unavailable");}finally{setBusy(false);}}
 return <section className="weather-card"><h3>Weather near your garden</h3><p>Choose your area for a live forecast.</p><select aria-label="Weather area" value={place} onChange={e=>{const cities:Record<string,[number,number]>={Pune:[18.52,73.86],Mumbai:[19.08,72.88],Nashik:[20,73.79],Bengaluru:[12.97,77.59],Delhi:[28.61,77.21]};setPlace(e.target.value);setWeather(null);const point=cities[e.target.value];if(point)void load(...point,e.target.value);}}>{["Pune","Mumbai","Nashik","Bengaluru","Delhi",...(place==="My area"?["My area"]:[])].map(p=><option key={p}>{p}</option>)}</select>
 <button className="text-button" disabled={busy} onClick={()=>{if(place==="Pune")void load(18.52,73.86,"Pune");else {const cities:Record<string,[number,number]>={Mumbai:[19.08,72.88],Nashik:[20,73.79],Bengaluru:[12.97,77.59],Delhi:[28.61,77.21]};const point=cities[place];if(point)void load(...point,place);else setError("Choose Use my location to refresh this area.");}}}>{busy?"Loading…":"Load forecast"}</button>
 <button className="text-button" disabled={busy} onClick={()=>{if(!navigator.geolocation){setError("Location is not supported. Choose a city.");return;}setBusy(true);navigator.geolocation.getCurrentPosition(p=>void load(p.coords.latitude,p.coords.longitude,"My area"),()=>{setBusy(false);setError("Location was unavailable. Choose a city instead.");},{timeout:10000,maximumAge:300000,enableHighAccuracy:false});}}>Use my location</button><p><small>Location is rounded before requesting weather; it is not posted publicly.</small></p>
 {error&&<p role="status">{error}</p>}{weather&&<><div className="weather-main"><strong>{Math.round(weather.temperature)}°C</strong></div><p>{weather.humidity}% humidity · {weather.wind} km/h wind</p><p>Rain probability this hour: {weather.rainProbability===null?"Unavailable":`${weather.rainProbability}%`}</p><small>Forecast time: {weather.time.replace("T"," ")} ({weather.timezone})</small><p>Check soil moisture before watering. Weather alone does not diagnose plant health.</p><a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Weather data by Open-Meteo</a></>}
 </section>;
}
